using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestGeneratorLib.Tests
{
    [TestClass]
    public class TestClassTests
    {
        [TestMethod]
        public void testTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}
