using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestsGeneratorTests.stuff.actual.Tests
{
    [TestClass]
    public class Actual2Tests
    {
        [TestMethod]
        public void test1Test()
        {
            Assert.Fail("autogenerated");
        }
        [TestMethod]
        public void test2Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}
